const express = require('express');
const crypto = require('crypto');
const bcrypt = require('bcryptjs');
const { pool } = require('../db');
const { protect, authorize } = require('../Middleware/auth');
const router = express.Router();
const transitions = { PENDING: ['ACCEPTED', 'REJECTED', 'CANCELLED'], ACCEPTED: ['ON_THE_WAY', 'CANCELLED'], ON_THE_WAY: ['ARRIVED', 'CANCELLED'], ARRIVED: ['IN_PROGRESS'], IN_PROGRESS: ['COMPLETED', 'DISPUTED'], DISPUTED: [] };
const select = `SELECT b.*,s.name AS service_name,w.name AS worker_name,c.name AS customer_name FROM bookings b JOIN services s ON s.id=b.service_id JOIN users w ON w.id=b.worker_id JOIN users c ON c.id=b.customer_id`;

router.post('/', protect, authorize('customer'), async (req, res) => { const { workerId, serviceId, bookingDate, address, description, amount } = req.body; if (!workerId || !serviceId || !bookingDate || !address?.trim() || !Number.isFinite(Number(amount)) || Number(amount) < 0) return res.status(400).json({ success: false, message: 'Worker, service, date, address and valid amount are required' }); try { const [workers] = await pool.query('SELECT user_id FROM worker_profiles WHERE id=? AND verified=TRUE AND available_now=TRUE', [workerId]); if (!workers[0]) return res.status(409).json({ success: false, message: 'Worker is no longer available' }); const [services] = await pool.query('SELECT id FROM services WHERE id=? AND is_active=TRUE', [serviceId]); if (!services[0]) return res.status(404).json({ success: false, message: 'Service not found' }); const code = `CS${Date.now().toString().slice(-7)}${crypto.randomInt(10, 99)}`; const [result] = await pool.query('INSERT INTO bookings (booking_code,customer_id,worker_id,service_id,booking_date,address,description,amount) VALUES (?,?,?,?,?,?,?,?)', [code, req.user.id, workers[0].user_id, serviceId, new Date(bookingDate), address.trim(), description || '', Number(amount)]); const [rows] = await pool.query(`${select} WHERE b.id=?`, [result.insertId]); res.status(201).json({ success: true, booking: rows[0] }); } catch { res.status(500).json({ success: false, message: 'Booking failed' }); } });

router.get('/my', protect, async (req, res) => { try { const column = req.user.role === 'worker' ? 'worker_id' : 'customer_id'; const [bookings] = await pool.query(`${select} WHERE b.${column}=? ORDER BY b.created_at DESC`, [req.user.id]); res.json({ success: true, bookings }); } catch { res.status(500).json({ success: false, message: 'Unable to load bookings' }); } });

router.patch('/:id/status', protect, async (req, res) => { const nextStatus = String(req.body.status || '').toUpperCase(); if (!transitions[nextStatus] && nextStatus !== 'COMPLETED') return res.status(400).json({ success: false, message: 'Invalid booking status' }); try { const [rows] = await pool.query('SELECT * FROM bookings WHERE id=?', [req.params.id]); const booking = rows[0]; if (!booking || (req.user.role === 'worker' ? booking.worker_id !== req.user.id : booking.customer_id !== req.user.id)) return res.status(404).json({ success: false, message: 'Booking not found' }); if (!transitions[booking.status]?.includes(nextStatus)) return res.status(409).json({ success: false, message: `Cannot move booking from ${booking.status} to ${nextStatus}` }); await pool.query('UPDATE bookings SET status=? WHERE id=?', [nextStatus, booking.id]); const [updated] = await pool.query(`${select} WHERE b.id=?`, [booking.id]); res.json({ success: true, booking: updated[0] }); } catch { res.status(500).json({ success: false, message: 'Unable to update booking' }); } });

router.put('/:id/accept', protect, authorize('worker'), async (req, res) => { try { const [result] = await pool.query('UPDATE bookings SET status="ACCEPTED" WHERE id=? AND worker_id=? AND status="PENDING"', [req.params.id, req.user.id]); if (!result.affectedRows) return res.status(409).json({ success: false, message: 'Booking cannot be accepted' }); const [rows] = await pool.query(`${select} WHERE b.id=?`, [req.params.id]); res.json({ success: true, booking: rows[0] }); } catch { res.status(500).json({ success: false, message: 'Unable to accept booking' }); } });
router.put('/:id/cancel', protect, async (req, res) => { req.body.status = 'CANCELLED'; const [rows] = await pool.query('SELECT * FROM bookings WHERE id=? AND customer_id=?', [req.params.id, req.user.id]); if (!rows[0]) return res.status(404).json({ success: false, message: 'Booking not found' }); if (!transitions[rows[0].status]?.includes('CANCELLED')) return res.status(409).json({ success: false, message: 'Booking can no longer be cancelled' }); await pool.query('UPDATE bookings SET status="CANCELLED" WHERE id=?', [req.params.id]); res.json({ success: true, message: 'Booking cancelled' }); });
module.exports = router;